name: Integration Suite

on: ['push']

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/master' }}

env:
  NPM_CONFIG_LOGLEVEL: warn

jobs:
  integrate:
    name: Integration
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: "8"
          cache: 'npm'

      - name: Installing Dependencies
        run: npm ci

      - name: Compiling Code
        run: npm run build

      - name: Linting Code
        run: npm run lint

      - name: Checking for Duplication
        run: npm run duplication -- --limit 15

  release:
    name: Semantic Release
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-node@v3
      with:
        node-version: "8"
        cache: 'npm'

    - name: Semantic Release
      if: github.ref == 'refs/heads/master'
      run: npx ts-node src/deploy.ts
      env:
        GITHUB_TOKEN: ${{ secrets.SEMANTIC_RELEASE_GITHUB_TOKEN }}
